tasks:
  - init: |
      pip install mkdocs-material mkdocs-minify-plugin mkdocs-redirects mkdocs-git-revision-date-localized-plugin mkdocs-awesome-pages-plugin pymdown-extensions mkdocs-glightbox
    command: mkdocs serve

ports:
  - port: 8000
    onOpen: notify
