site_name: Study Harder
site_url: https://study-harder.pages.dev/
site_author: Qin Guan
copyright: Copyright &copy; Qin Guan CC BY-NC-SA 4.0

repo_url: https://github.com/qin-guan/study-harder
repo_name: qin-guan/study-harder
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.arithmatex

plugins:
  - search
  - awesome-pages
  - social
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [ CI, false ]

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
