site_name: Study Harder
site_url: https://study-harder.pages.dev/
site_author: Qin Guan
copyright: Copyright &copy; Qin Guan <a href="https://github.com/qin-guan/study-harder/blob/main/LICENSE">CC BY-NC-SA 4.0</a>

repo_url: https://github.com/qin-guan/study-harder
repo_name: qin-guan/study-harder
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - tables
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - attr_list
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

plugins:
  - search
  - social
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [ CI, false ]

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
